<<<<<<< HEAD
const ResMessage = {
    list : (name) => name + " lists are",
        exists: (exists) => exists +" already exists",
        details :(details) => details+ " details are",
        added : (added) =>  added+" added successfully",
        updated: (updated) => updated+" updated successfully",
        failed: (failed) => "Failed to update "+failed,
        deleted: (deleted) => deleted+" deleted successfully",
    1 : 'Admin Created Successfully',
    2 : 'invalid credentials',
    3 : 'Your account has been disabled due to too much of Login attempts. Try again after in 5 Mins',
    4 : 'Please verify your email address',
    5 : 'Your account has been deactivated',
    6 : 'Incorrect password',
    7 : 'Verification OTP sent your registered email address',
    8 : 'Invalid otp',
    9 : 'Login successfully',
    10 : 'New password and confirm password doesn\'t match',
    11 : 'New password cannot be the same as your current password',
    12 : 'Invalid current password',
    13 : 'Password already exists. Please try with another one',
    14 : 'Password changed successfully',
    15 : 'Email already exists!',
    16 : 'Phone number already exist!',
    17 : 'User Created',
    18 : 'Please Provide Valid Data',
    19 : 'Email already exists',
    20 : 'Phone number already exists. Please try with another one',
    21 : 'Your account has been disabled due to too much of login attempts. Please contact admin',
    22 : 'Email doesn\'t exists',
    23 : 'Email has been sent successfully. Please check your inbox',
    24 : 'Please Enter valid data',
    25 : 'Unauthorized access',
    26 : 'OTP verified successfully',
    27 : 'OTP has expired',
    28 : 'Smonething went wrong',
    29 : 'New password and confirm password doesn\'t match',
    30 : 'User not found',
    31 : 'OTP verification failed',
    32 : 'Invalid token',
    33 : 'Password already exists. Please try with another one',
    34 : 'Your password has been reset sucessfully',
    35 : 'Status already in ',
    36 : 'Status updated successfully',
    37 : 'User details',
    38 : 'Something went wrong',
    39 : 'No Data Found',
    40 : 'Account Type Empty!',
    41 : 'Account Number is Empty',
    42 : 'Account number already Exist',
    43 : 'privileges not updated',
    44 : 'Invalid data received ',
    45 : 'Sub User deleted successfully',
    46 : 'Merchant deleted successfully',
    47 : 'Profile details'
};

=======
const ResMessage = {
    list : (name) => name + " lists are",
        exists: (exists) => exists +" already exists",
        details :(details) => details+ " details are",
        added : (added) =>  added+" added successfully",
        updated: (updated) => updated+" updated successfully",
        failed: (failed) => "Failed to update "+failed,
        deleted: (deleted) => deleted+" deleted successfully",
    1 : 'Admin Created Successfully',
    2 : 'invalid credentials',
    3 : 'Your account has been disabled due to too much of Login attempts. Try again after in 5 Mins',
    4 : 'Please verify your email address',
    5 : 'Your account has been deactivated',
    6 : 'Incorrect password',
    7 : 'Verification OTP sent your registered email address',
    8 : 'Invalid otp',
    9 : 'Login successfully',
    10 : 'New password and confirm password doesn\'t match',
    11 : 'New password cannot be the same as your current password',
    12 : 'Invalid current password',
    13 : 'Password already exists. Please try with another one',
    14 : 'Password changed successfully',
    15 : 'Email already exists!',
    16 : 'Phone number already exist!',
    17 : 'User Created',
    18 : 'Please Provide Valid Data',
    19 : 'Email already exists',
    20 : 'Phone number already exists. Please try with another one',
    21 : 'Your account has been disabled due to too much of login attempts. Please contact admin',
    22 : 'Email doesn\'t exists',
    23 : 'Email has been sent successfully. Please check your inbox',
    24 : 'Please Enter valid data',
    25 : 'Unauthorized access',
    26 : 'OTP verified successfully',
    27 : 'OTP has expired',
    28 : 'Smonething went wrong',
    29 : 'New password and confirm password doesn\'t match',
    30 : 'User not found',
    31 : 'OTP verification failed',
    32 : 'Invalid token',
    33 : 'Password already exists. Please try with another one',
    34 : 'Your password has been reset sucessfully',
    35 : 'Status already in ',
    36 : 'Status updated successfully',
    37 : 'User details',
    38 : 'Something went wrong',
    39 : 'No Data Found',
    40 : 'Account Type Empty!',
    41 : 'Account Number is Empty',
    42 : 'Account number already Exist',
    43 : 'privileges not updated',
    44 : 'Invalid data received ',
    45 : 'Sub User deleted successfully',
    46 : 'Merchant deleted successfully',
    47 : 'Profile details'
};

>>>>>>> origin/dev
module.exports = {ResMessage};